# -*-visEmacs-*-
# Use this open statement to create a .prim file suitable for
# viewing in DAWN or OGL:
#/vis/open DAWNFILE
#/vis/open OGLIX
/vis/open OGLSX 2000
#
########### Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
#/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 30 32 deg
#
# Specify zoom value:
/vis/viewer/zoom 3
#
# Change the center
/vis/viewer/panTo -2 -2
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 10 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-1/add opticalphoton
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu- brown
#/vis/modeling/trajectories/drawByParticleID-1/set mu- brown
/vis/modeling/trajectories/drawByParticleID-0/set e- green
#/vis/modeling/trajectories/drawByParticleID-1/set e- green
/vis/modeling/trajectories/drawByParticleID-0/set gamma magenta
#/vis/modeling/trajectories/drawByParticleID-1/set gamma magenta
#/vis/modeling/trajectories/drawByParticleID-1/set opticalphoton cyan
#
#/control/execute colours.mac
#
#
#
#
###########  To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
###########  Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
#/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#
/run/beamOn 1
#########/score/dumpQuantityToFile boxMesh_1 nbOptical scoreOptical.txt
#/score/drawProjection boxMesh_1 nbOptical
